spring:
  application:
    name: finar
  datasource:
    url: jdbc:postgresql://localhost/finar?user=app&password=password
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  security:
    user:
      name: user
      password: password
  data:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  servlet:
    session:
      timeout: 60s
  port: 8000
logging:
  level:
    root: WARN
    org.springframework:
      web: DEBUG
    com.skyegibney.finar:
      game: DEBUG
      notifications: DEBUG
      matchmaking: DEBUG
      websockets: DEBUG
      authorization: DEBUG

logging.level.com.skyegibney.finar.game: DEBUG
logging.level.com.skyegibney.finar.notifications: DEBUG
