name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn clean package
      - run: mkdir app && cp target/*.jar src/main/resources/application-prod.yml src/main/resources/application.yml app
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: app
  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Package
          path: app
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: 'kill $(ps -ef | grep finar | awk ''{print $2}'') || true; rm -rf /app'
      - uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          source: app/*
          target: /
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: 'cd /app; nohup java -jar ./*.jar -Dspring.profiles.active=prod > spring-log.txt'